version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: workflow-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workflow-network

  temporal:
    container_name: workflow-temporal
    image: temporalio/admin-tools:1.22.4
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    entrypoint: /bin/sh -c "while ! nc -z temporal 7233; do sleep 1; done;"
    depends_on:
      - temporal-server
    networks:
      - workflow-network

  temporal-server:
    container_name: temporal
    image: temporalio/auto-setup:1.22.4
    ports:
      - '7233:7233'
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    depends_on:
      - postgres
    networks:
      - workflow-network

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:2.21.3
    ports:
      - '8080:8080'
    environment:
      - TEMPORAL_ADDRESS=temporal-server:7233
    depends_on:
      - temporal-server
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge

volumes:
  postgres_data:
